spring.application.name=rpg-backend

spring.datasource.url=jdbc:postgresql://localhost:5432/rpgdb
spring.datasource.username=rpg
spring.datasource.password=rpg

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
